alias vscode='/usr/bin/code'
alias chrome='google-chrome-stable'
alias netflix='chrome --app=https://netflix.com'
alias pacman='sudo pacman'
alias search='sudo find / -name'
alias mn='sudo mn'
alias p='ping 8.8.8.8'
alias telegram='~/apps/Telegram/./Telegram'
alias dropbox='~/apps/.dropbox-dist/./dropboxd start -i'
