alias apt="sudo nala"
alias cat="batcat"
alias apt-snap="~/apps/./clean_snap.sh"
alias ls="eza --icons --group-directories-first"
alias l="ls -a"
alias ll="eza -l --git --icons --color-scale -h -g --group-directories-first"
alias la="ll -a"
alias tree="eza --tree --icons --level 2 --group-directories-first"
alias find="fdfind"
alias poweroff="sudo poweroff"
alias reboot="sudo reboot"
alias vim="nvim"
alias apt-livepatch='sudo canonical-livepatch refresh'
alias 2dark="ln -fs ~/.config/alacritty/themes/one_dark.toml ~/.config/alacritty/themes/active.toml"
alias 2light="ln -fs ~/.config/alacritty/themes/github_light.toml ~/.config/alacritty/themes/active.toml"
alias dufiles="du -hsc * | sort -h"
alias dudirs="du -h --max-depth=1 | sort -h"
alias cpenv="python3 -m venv .venv"
alias apenv=". .venv/bin/activate"

