alias vscode='/usr/bin/code'
alias chrome='google-chrome-stable'
alias netflix='chrome --app=https://netflix.com'
alias calendar='chrome --app=https://calendar.google.com'
alias apt='sudo apt'
alias search='sudo find / -name'
alias p='ping 8.8.8.8'
alias telegram='~/apps/Telegram/./Telegram'
alias dropbox='~/apps/.dropbox-dist/./dropboxd start -i'
alias cat='bat'
